### ISSUE TITLE
Remove jQuery dependency

### ISSUE THREAD

**Issue by goldenapples** [humanmade/altis-consent#10]
A suggestion for this release: is it feasible to remove the jQuery dependency here? I think that most new sites using this won't have jQuery already enqueued, so adding the extra 30k to enqueue the library will hurt performance.

It looks like jQ is mainly used for adding click event listeners and adding/removing classes, and all modern browsers should support DOM functionality like `addEventListener` and `classList`.

**Comment by roborourke** [comment]
Agree this would be good to do for the initial release. @jazzsequence how much effort do you think this would be? Happy to assist with it.

**Comment by jazzsequence** [comment]
jQuery is required [by the Consent API itself](https://github.com/rlankhorst/wp-consent-level-api/blob/master/api.php#L45), so if we're building something on top of that, then it would be enqueued already, which is why I was using it.

That said, that dependency could be removed (especially considering the [actual js file](https://github.com/rlankhorst/wp-consent-level-api/blob/master/assets/js/wp-consent-api.js) doesn't actually use it -- I thought it did, but I was thinking of the [example plugin](https://github.com/rlankhorst/consent-api-example-plugin/blob/master/main.js)).

I don't imagine swapping jQuery out to be more than a day's effort. Mostly it's just shortcutting some variables and hooks.

**Comment by jazzsequence** [comment]
Also filed an issue on [the consent API repo](https://github.com/rlankhorst/wp-consent-level-api/issues/57) to remove the jQuery dependency. If there's no particular reason it's required, I can open a PR over there, too.

**Comment by roborourke** [comment]
Ah I see. Lets have a look at how complex the code is. I imagine it was just used for speed of development and convenience but modern DOM functions make most things like selectors and event handling pretty trivial.

**Comment by jazzsequence** [comment]
Their js file doesn't actually use any jQuery, but it's part of the `wp_enqueue_script`. We can still remove it from our end, though. 👍

**Comment by roborourke** [comment]
Oh weird. Yeah let's do that then :) Maybe it got refactored but the dependency never removed.

**Comment by jazzsequence** [comment]
Yep, looks like that's what happened. The [first iteration](https://github.com/rlankhorst/wp-consent-level-api/commit/c16d3f47f3beb5d66cbb9d5bf966a5d861d2e21d#diff-46eeea02642fc062b5711f2badc000b6) of the js file used jQuery, but it was [removed later](https://github.com/rlankhorst/wp-consent-level-api/commit/11b18885119f9797286cd4e429cec7693371e6a7#diff-46eeea02642fc062b5711f2badc000b6).

I will open a PR over there, too then to remove the dependency in the enqueue since it's likely that just never got pulled out.

**Comment by jazzsequence** [comment]
[PR](https://github.com/rlankhorst/wp-consent-level-api/pull/58) in upstream repo

**Comment by jazzsequence** [comment]
This is removed in upstream as of https://github.com/rlankhorst/wp-consent-level-api/commit/6c8d93f767d4d2721bd3edd75f767af732faee42

**Comment by roborourke** [comment]
Amazing, glad you could contribute upstream! Nice work Chris
