### ISSUE TITLE
Auto-generate Privacy Policy and Cookie Policy pages

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/altis-consent#16]
## Description
WordPress core has a button which creates a new privacy policy page if you don't have one. Since we've removed their privacy page and replaced it with our own, we lack that ability. If a privacy policy page is not set, it returns an empty string when the url is attempted to be retrieved with `get_privacy_policy_url`.

Our own functionality for `get_cookie_policy_url` behaves the same way and is modeled after the same functionality. 

It would be good to automatically generate these pages if they do not exist (or on demand) so that those pages can be set and we are never linking to an empty string, and to remove some of the responsibility on the site owner to produce these pages.

This would require agreeing on and supplying some default content for both the privacy policy page (which we may be able to get from WP core) and the cookie policy page (which we might be able to get from the Complianz plugin).

**Comment by jazzsequence** [comment]
cc: @PriyaBhatia0210 @roborourke

**Comment by PriyaBhatia0210** [comment]
For the privacy policy page, we can still default to the WP core page that we removed, right? More so that, it doesn't create confusion in a user that something has been removed (privacy page) to incorporate something else (cookie page). Just trying to ensure continuity of experience for a user who is familiar with WP core.

**Comment by jazzsequence** [comment]
> we can still default to the WP core page that we removed, right?

There's a bit of a workaround in place to make the pieces fit together, but the short answer is, if an existing privacy policy page exists, we keep that setting. This question is more about the fact that on a new site, you don't have those pages yet. And in core, there's a Create New Page button (which, honestly, isn't clear that it creates a new page with Privacy Policy content on it vs just creating a new _blank_ page) which creates a Privacy Policy page for you (with generic content). 

Part of the reason that page is hard-coded in WordPress is because of that button. Essentially, there are two forms on the page -- one that handles the privacy policy page _setting_ and the other which is for the _button that creates the privacy policy page_. Out of necessity, because we want our page to be something that can be hooked into and changed, this was lost. 

However, it might be a better user experience _anyway_ to just generate those pages so site admins can just change them later, and that's what this ticket is for.

**Comment by roborourke** [comment]
@jazzsequence to get that functionality back you could use a named submit button - then if that is set you could execute the backend logic that generates the privacy policy page, otherwise you could carry out the standard form actions.

I'd prefer not to lose the built in capability because it provides hooks for adding in default content that we documented in the core module. Also I was hoping we could use those same hooks to add our own default content for native analytics.

**Comment by jazzsequence** [comment]
@roborourke I don't know if I was giving too much credit to WordPress core or if I didn't try enough different things but somehow I missed this and thought it wasn't possible. I agree that this should be included in the MVP.

**Comment by jazzsequence** [comment]
Closed via https://github.com/humanmade/altis-consent/pull/18
